#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
disable_notice = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = 'path'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = '  {{ path .Path .Location }} '
background = 'blue'
foreground = 'transparent'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'powerline'
powerline_symbol = ''
background_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}',
  '{{ if gt .Ahead 0 }}magenta{{ end }}',
  '{{ if gt .Behind 0 }}magenta{{ end }}',
]
template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
background = 'green'
foreground = 'transparent'

[blocks.segments.properties]
branch_max_length = 25
fetch_status = true
fetch_upstream_icon = true


[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = "executiontime"
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
foreground = "transparent"
background = "magenta"
template = "  {{ .FormattedMs }} "

[properties]
threshold = 100
style = "austin"
always_enabled = true

[[blocks.segments]]
type = 'time'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = ' {{ .CurrentDate | date "03:04 PM" }} '
background = 'blue'
foreground = 'transparent'


[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}green{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
template = '❯❯ '
foreground = 'green'
