-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:Chimei Innolux Corporation 0x143B",
  mode = "1920x1200@60.003",
  position = "0x800",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL P2725DE DB3XQC4",
  mode = "2560x1440@99.946",
  position = "1920x560",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL U2713H C6F0K4AL0PDL",
  mode = "2560x1440@59.951",
  position = "4480x0",
  scale = 1,
  transform = 1,
  vrr = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
